// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zysukznqguraindbbjjg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp5c3Vrem5xZ3VyYWluZGJiampnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MTg3NzUsImV4cCI6MjA2NTQ5NDc3NX0.XO5C3SHtXmSm2FFyCg5sJMo7-aYZmoAPlqlQaef-brw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);